name: Build Push Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/wisecow:${{ github.sha }}
        outputs: type=registry

    - name: Save image tag
      run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/wisecow:${{ github.sha }}" >> $GITHUB_ENV

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Restore kubeconfig
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Update k8s manifests image
      run: |
        kubectl set image deployment/wisecow wisecow=$IMAGE --namespace default || \
        (kubectl apply -f k8s/deployment.yaml && kubectl apply -f k8s/service.yaml)

    - name: Ensure ingress (optional)
      run: kubectl apply -f k8s/ingress.yaml || true
