name: Deploy Wisecow to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1   # 👈 change if needed

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name <YOUR-CLUSTER-NAME> --region ap-south-1
          kubectl config view --minify
          kubectl get nodes
